// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// GUniFracCpp
List GUniFracCpp(arma::mat cum, arma::mat brlen);
RcppExport SEXP MiSPU_GUniFracCpp(SEXP cumSEXP, SEXP brlenSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type cum(cumSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type brlen(brlenSEXP);
    __result = Rcpp::wrap(GUniFracCpp(cum, brlen));
    return __result;
END_RCPP
}
// GUniFracCpp2
arma::cube GUniFracCpp2(arma::mat cum, arma::mat brlen, arma::mat powV);
RcppExport SEXP MiSPU_GUniFracCpp2(SEXP cumSEXP, SEXP brlenSEXP, SEXP powVSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type cum(cumSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type brlen(brlenSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type powV(powVSEXP);
    __result = Rcpp::wrap(GUniFracCpp2(cum, brlen, powV));
    return __result;
END_RCPP
}
// MiSPUC
List MiSPUC(arma::mat X1, arma::mat r1, arma::mat X2, arma::mat r2, arma::mat powV, int nperm);
RcppExport SEXP MiSPU_MiSPUC(SEXP X1SEXP, SEXP r1SEXP, SEXP X2SEXP, SEXP r2SEXP, SEXP powVSEXP, SEXP npermSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type r1(r1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type r2(r2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type powV(powVSEXP);
    Rcpp::traits::input_parameter< int >::type nperm(npermSEXP);
    __result = Rcpp::wrap(MiSPUC(X1, r1, X2, r2, powV, nperm));
    return __result;
END_RCPP
}
// BCdist
arma::mat BCdist(arma::mat X, arma::mat weight);
RcppExport SEXP MiSPU_BCdist(SEXP XSEXP, SEXP weightSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type weight(weightSEXP);
    __result = Rcpp::wrap(BCdist(X, weight));
    return __result;
END_RCPP
}
