// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// GUniFracCpp
List GUniFracCpp(arma::mat cum, arma::mat brlen);
RcppExport SEXP MiSPU_GUniFracCpp(SEXP cumSEXP, SEXP brlenSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type cum(cumSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type brlen(brlenSEXP);
    __result = Rcpp::wrap(GUniFracCpp(cum, brlen));
    return __result;
END_RCPP
}
// GUniFracCpp2
arma::cube GUniFracCpp2(arma::mat cum, arma::mat brlen, arma::mat powV);
RcppExport SEXP MiSPU_GUniFracCpp2(SEXP cumSEXP, SEXP brlenSEXP, SEXP powVSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type cum(cumSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type brlen(brlenSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type powV(powVSEXP);
    __result = Rcpp::wrap(GUniFracCpp2(cum, brlen, powV));
    return __result;
END_RCPP
}
