# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GUniFracCpp <- function(cum, brlen) {
    .Call('MiSPU_GUniFracCpp', PACKAGE = 'MiSPU', cum, brlen)
}

GUniFracCpp2 <- function(cum, brlen, powV) {
    .Call('MiSPU_GUniFracCpp2', PACKAGE = 'MiSPU', cum, brlen, powV)
}

